# @package model.head

net:
  _target_: torch.nn.Conv3d
  in_channels: ${model.backbone.out_feat}
  kernel_size: ${model.backbone.out_spatial_shape}
  out_channels: 1

mask_padding_size: 0
dropout_prob: 0.3
