vae:
  _target_: connectomics_segmentation.models.VAE
  encoder:
    _target_: torch.nn.Identity
  decoder:
    _target_: torch.nn.Identity
  latent_dim: 512
  enc_out_feat_dim: 262144

kl_loss_weight: 0.5