# @package model

backbone_out_feat: ???

head:
  _target_: torch.nn.Sequential
  _args_:
  - _target_: torch.nn.Flatten
  - _target_: torch.nn.Linear
    in_features: ${model.backbone_out_feat}
    out_features: ${model.num_classes}