# @package model

head:
  _target_: torch.nn.Sequential
  _args_:
  - _target_: torch.nn.Flatten
  - _target_: torch.nn.Linear
    # in_features: 46656
    in_features: 512
    out_features: ${model.num_classes}