net:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: connectomics_segmentation.models.modules.Conv3DBlock
      in_features: 1
      out_features: 16
      kernel_size: 3
      activation: ${model.backbone.activation}
      norm: ${model.backbone.norm}
    - _target_: torch.nn.MaxPool3d
      kernel_size: 2
      stride: 2
    - _target_: connectomics_segmentation.models.modules.Conv3DBlock
      in_features: 16
      out_features: 32
      kernel_size: 3
      activation: ${model.backbone.activation}
      norm: ${model.backbone.norm}
    - _target_: torch.nn.MaxPool3d
      kernel_size: 2
      stride: 2
    - _target_: connectomics_segmentation.models.modules.Conv3DBlock
      in_features: 32
      out_features: 64
      kernel_size: 3
      activation: ${model.backbone.activation}
      norm: ${model.backbone.norm}
    - _target_: connectomics_segmentation.models.modules.Conv3DBlock
      in_features: 64
      out_features: 128
      kernel_size: 3
      activation: ${model.backbone.activation}
      norm: ${model.backbone.norm}
    - _target_: torch.nn.AvgPool3d
      kernel_size: 2
      stride: 2

activation: GELU
norm: batch
out_feat: 128
out_spatial_shape: 1