net:
  _target_: connectomics_segmentation.models.ConvNext
  _convert_: all
  in_channels: 1
  patch_size: 4
  depths: [3, 3, 9, 3]
  dims: [96, 192, 384, 768]
  drop_path_rate: 0.0

out_feat: 768
out_spatial_shape: 1