defaults:
  - _self_
  - supervised_simple

num_classes: 6
compile_model: True

loss:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: 6

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0005