defaults:
  - _self_
  - loss: focal
  - backbone: dilated_conv_2_layer
  - supervised: linear_head
  - unsupervised: null

num_classes: 6
compile_model: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0005