defaults:
  - _self_
  # - unsupervised/simple_vae
  - shared/dialated_conv_2_layer
  # - supervised/linear_head
  - unsupervised/linear_head

num_classes: 6
compile_model: True

# loss:
#   _target_: torch.nn.CrossEntropyLoss
#   ignore_index: 6
loss:
  _target_: torch.nn.MSELoss

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0005