net:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: connectomics_segmentation.models.modules.Conv3DBlock
      in_features: 1
      out_features: 5
      kernel_size: 3
    - _target_: connectomics_segmentation.models.modules.ResidualModule
      main_module:
        _target_: connectomics_segmentation.models.modules.Conv3DBlock
        in_features: 5
        out_features: 5
        kernel_size: 3
        padding: 1
    - _target_: torch.nn.Flatten
    - _target_: torch.nn.Linear
      in_features: 1191640
      out_features: ${model.num_classes}