net:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Conv3d
      in_channels: 1
      out_channels: 5
      kernel_size: 3
    - _target_: torch.nn.Flatten
    - _target_: torch.nn.Linear
      in_features: 1191640
      out_features: ${model.num_classes}
