optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.0005

num_classes: 6
compile_model: True

net:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Conv3d
      in_channels: 1
      out_channels: 5
      kernel_size: 3
    - _target_: torch.nn.Flatten
    - _target_: torch.nn.Linear
      in_features: 1191640
      out_features: ${model.num_classes}

loss:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: 6
