crf_postprocessing:
  _target_: connectomics_segmentation.callbacks.DenseCRFPostprocessingCallback
  _convert_: all
  image_width: 425
  image_height: 425
  n_classes: ${model.num_classes}
  class_names: ${data.class_names}
  calculate_metrics: True
  position_theta:
    - 1
    - 1
    - 1
  bilateral_theta: 1
  compat_position: 1
  compat_bilateral: 1
  num_steps: 10
  subvolume_size: ${data.devel_subvolume_size}
