crf_postprocessing:
  _target_: connectomics_segmentation.callbacks.DenseCRFPostprocessingCallback
  _convert_: all
  image_width: 425
  image_height: 425
  n_classes: ${model.num_classes}
  class_names: ${data.class_names}
  calculate_metrics: True
  position_theta:
    - 1
    - 1
    - 1
  bilateral_theta: 1
  compat_position: 1
  # compat_bilateral: 5
  compat_bilateral: [0,   1.0, 100, 1.0, 1.0, 100, 1.0, 0,   100, 10,  0.5, 100, 100, 100, 0,   5.0, 100, 100, 1.0, 10,  5.0, 0,   100, 100, 1.0, 0.5, 100, 100, 0,   100, 100, 100, 100, 100, 100, 0]
  num_steps: 10
  subvolume_size: ${data.devel_subvolume_size}
