test_visualization:
  _target_: connectomics_segmentation.callbacks.TestVisualizationCallback
  image_width: 425
  image_height: 425
  n_classes: ${model.num_classes}
  class_names: ${data.class_names}
  subvolume_size: ${data.devel_subvolume_size}
