defaults:
  - _self_
  - hydra: default
  - paths: default
  - data: raw_data
  - model: default
  - trainer: supervised_default
  - loggers: null
  - experiment: null
  - callbacks: inference

task_name: inference

class_names:
  - intra_cellular_space
  - cellular_membrane
  - intra_mitochondrial_space
  - mitochondrial_membrane
  - synapse
  - vesicle

ckpt_path: ???

seed: null
