defaults:
  - _self_
  - data: labeled_data
  - model: default
  - loggers: default
  - trainer: supervised_default
  - paths: default
  - hydra: default
  - callbacks: supervised
  - experiment: null

task_name: train

supervised: True
run_test: True

pretrained_ckpt_path: null
load_vae_mean_head: False
ckpt_path: null  # checkpoint path to resume training

seed: null
