defaults:
  - data: labeled_data
  - model: default
  - loggers: default
  - trainer: default
  - paths: default
  - hydra: default
  - callbacks: default
  - experiment: null
  - _self_

task_name: train

supervised: True
run_test: True

pretrained_ckpt_path: null
load_vae_mean_head: False
ckpt_path: null  # checkpoint path to resume training

seed: null
